### ISSUE TITLE
open in browser but only once

### ISSUE THREAD

**Issue by mike3run** [c8r/x0#23]
I think here it'd good to use the `open` command from `react-dev-tools` to just open the browser once (like what create-react-app) since it does that but fallsback to `opn` if you're not on chrome on a mac...

https://github.com/facebookincubator/create-react-app/tree/master/packages/react-dev-utils#openbrowserurl-string-boolean.

Here's how they do it:

https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/scripts/start.js#L85

lmk i could send a PR to help 😄

**Comment by johnotander** [comment]
I think that'd be a great addition to improve the experience. We'd be happy to accept a PR for this if you wanted to lend a hand 💙 .

**Comment by mike3run** [comment]
sure thing 😄 i just wanted to get an ok in an issue first before doing that work haha, i'll get it done today

**Comment by mike3run** [comment]
Ready for you to check/merge https://github.com/c8r/x0/pull/24
