### ISSUE TITLE
Minify the rendered HTML.

### ISSUE THREAD

**Issue by stefanjudis** [c8r/x0#27]
Hey folks! 👋 

I just came along and this looks great. Especially when I discovered that x0 support `--static`. One question though. By simply building the example I noticed the HTML is not minified. Is this something to come or how should I approach this?

```
<!DOCTYPE html>
<meta charset='utf-8'>

<h1>Hello</h1>
```

But great job! 10min playing around with it was fun already.

**Comment by jxnblk** [comment]
Thanks for the question! I think this would be a great feature to add to the current static renderer. The React portion of the site should be minified by default, but the rest of the HTML is coming from the template here: https://github.com/c8r/x0/blob/master/lib/static/index.js#L19-L30

**Comment by johnotander** [comment]
This is now supported in the latest version of `x0`, `3.0.4`.
