### ISSUE TITLE
Support images for dev mode

### ISSUE THREAD

**Issue by KarafiziArtur** [c8r/x0#33]
By `yarn build` all images display correctly but they are missing in development mode. @jxnblk, could you please provide a solution for displaying them?
I use `glamorous`.

**Comment by KarafiziArtur** [comment]
I've tried to configure the Webpack's `config.js`, but it didn't help. None of the images displayed. Even by using `import`. Is there any solution?

**Comment by KarafiziArtur** [comment]
@jxnblk , could you please take a time to advise how can I fix this bug by myself? I would be appreciated.

**Comment by KarafiziArtur** [comment]
@Primigenus , @johnotander , @mrmrs , @jxnblk , @lachlanjc does anyone have the same problem with images in dev mode or it just in our case?

**Comment by jxnblk** [comment]
If you're trying to import images with a webpack-loader, previous versions of x0 did not use webpack on the node/server side. With 3.2.0, you can point to a custom [webpack config](https://github.com/c8r/x0#webpack)

Also, linking to relative images in the same folder should work (e.g. `<img src='kitten.gif' />`).

**Comment by KarafiziArtur** [comment]
Thanks! It works.
