### ISSUE TITLE
Local directory exposed on production build

### ISSUE THREAD

**Issue by robinvdvleuten** [c8r/x0#49]
When I build my project to static files, I see that in the `__initial-props__` script tag my current working path is exposed;

```html
<script id="__initial-props__" type="application/json">
  {"o":true,"open":true,"c":"webpack.config.js","config":"/Users/robinvdvleuten/Projects/*****/webpack.config.js","d":"build","outDir":"build"}
</script>
```

Is this necessary? I can imagine that this is unneeded when the project is already built.

**Comment by johno** [comment]
That's definitely a prop we should remove for production builds.

**Comment by johno** [comment]
This is now fixed by v5. Let us know if you encounter any other issues.
