### ISSUE TITLE
"content-type" is null, should be "text/html"

### ISSUE THREAD

**Issue by johnlindquist** [c8r/x0#50]
When running `x0` through Cypress, Cypress errors out:

```
http://localhost:4321/basic

The content-type of the response we received from your web server was:

  > null

This was considered a failure because responses must have content-type: 'text/html'
```

I assume "text/html" should be the default for content-type. I've been trying to find where to set the `content-type` in the webpack config, but not having any luck.

**Comment by johno** [comment]
Thanks for reporting this issue. This is now fixed in v5. Please let us know if you encounter any other issues.
