### ISSUE TITLE
Server doesn't start

### ISSUE THREAD

**Issue by allforabit** [c8r/x0#69]
I'm having an issue getting the tool to start. It gets stuck on "starting dev server" and just spins infinitely. I've tried debugging a bit but I can't see what's causing the issue. I'm running on OSX, node 8.11.3 and I've tried it as a local dev dependency (via yarn) and as a global but I'm still not having any luck. It starts the dev server if the folder is empty but it just hangs if there's a jsx file in it. If there are any other details that might help to figure out where the issue might be, let me know.

Thanks the tool looks great and is exactly what I've been look for. Would love to get it working!

**Comment by johno** [comment]
Thanks for opening up an issue. Do you mind including your npm version, x0 version, and the file name/contents?

**Comment by allforabit** [comment]
The npm version is 5.6.0 and x0 is 5.0.8. Here's a very simple example that I'm trying to run, by using `yarn x0 examples`. https://github.com/allforabit/x0-test By the way yarn version is 1.7.0. I've tried using the global version as well but it still gets stuck at the "starting dev server" step. When it's in this state it's not possible to properly exit as well. I.e. pressing c-c makes it stop briefly but then it comes back with the "starting dev server" message. Oddly enough I'm having the same issue on Windows.

**Comment by jxnblk** [comment]
Thanks! There's currently a bug where if something errors during startup, it doesn't throw an error or show any messaging. Looking at your repo, I think that the `.jsx` file extension is being picked up by [jsx-loader](https://github.com/c8r/jsx-loader) - can you try renaming the file to use the `.js` extension?

**Comment by allforabit** [comment]
Yes that's it! I also had a syntax error in my example that showed up in the browser console once I changed it to `.js`. Thanks very much and thanks for all the amazing tools!
