### ISSUE TITLE
404 Page

### ISSUE THREAD

**Issue by imhuyqn** [c8r/x0#77]
Thank you guys for creating this. I love it so much!

I have this question:
Can we make a custom 404 page?

**Comment by jxnblk** [comment]
Added in v6, the docs are still WIP, so please let us know how they could be better:
https://compositor.io/x0/routing#404-page

**Comment by gangstafat** [comment]
It's actually helpful in my development process. I just don't want people to see all the messy routes on that page when the site is published. Does it make any sense?
