### ISSUE TITLE
dev server not working for me...what am I doing wrong?

### ISSUE THREAD

**Issue by rchrdnsh** [c8r/x0#88]
so, I followed the steps up to starting the dev server by typing:

```
x0 docs --open
```

...but I get an error in the terminal in VS Code:

<img width="930" alt="screenshot 2018-08-03 07 58 54" src="https://user-images.githubusercontent.com/7884263/43649839-165866ac-96f3-11e8-8b6a-a21b66499136.png">

...so I'm not sure what to do next. Nothing is running in the terminal and nothing is running at localhost:8080 either.

¯\_(ツ)_/¯

**Comment by johno** [comment]
Looks like you might need to cd back a level (`cd ..`)? Seems like its trying to find `Code/x0/docs/docs` which makes it sound you might already be in the docs directory.

**Comment by rchrdnsh** [comment]
hmmmm...that worked...although,

it would be chill to be able to start up a dev server from within the project folder as well.

I tried running:

```
x0 -o
```

thinking that would work, but it didn't :-(

but in any case, it's working now, so thank you :-)
